Repository queens-psyc-clinic/app, pull requests merged in 2024-04, with the labels that each got.

#190 Shopping cart functionality + Requests Page + Signed out mark as picked up
  app/resources/loan.py
  client/src/components/Card.tsx
  client/src/components/CardsModal.tsx
  client/src/components/Cart.tsx
  client/src/components/ReserveModal.tsx
  client/src/components/SignedOutTable.tsx
  client/src/models/BEModels.ts
  client/src/models/libraryItem.ts
  client/src/models/tableColumns.ts
  client/src/pages/Dashboard.tsx
  client/src/pages/LowStock.tsx
  client/src/pages/Requests.tsx
  client/src/pages/SignedOut.tsx
  client/src/pages/StudentPage.tsx
  client/src/services/ShoppingCartService.ts
  client/src/services/TestService.ts
  db/db_setup/setup_db.sql
Labels: ready for review 👀, big boi

#196 FE Changes
  client/src/assets/logo.png
  client/src/components/Card.tsx
  client/src/components/Navbar.tsx
  client/src/components/PasswordModal.tsx
  client/src/components/ReportIssueModal.tsx
  client/src/pages/AccountType.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Overdue.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/SignedOut.tsx
Labels: ready for review 👀, big boi

#210 Student Pages, error handling for nonexistent users
  client/src/pages/StudentPage.tsx
Labels: ready for review 👀, small boi, fix

#211 Forgot password functionality
  app/app.py
  client/src/PrivateRoutes.tsx
  client/src/components/PasswordModal.tsx
  client/src/pages/SignIn.tsx
  client/src/services/UserService.ts
Labels: ready for review 👀

#231 FE Notes in Table and Add & Edit Modals
  client/src/components/FormItem.tsx
  client/src/components/Navbar.tsx
  client/src/components/Table.tsx
  client/src/models/BEModels.ts
Labels: ready for review 👀, Small PR

#203 Create notification api endpoints
  app/app.py
  app/resources/createNotification.py
  app/resources/notification.py
  app/resources/notifications.py
  db/db_setup/setup_db.sql
Labels: ready for review 👀

#228 FE Implementing Feedback
  client/src/components/Cart.tsx
  client/src/components/EditModal.tsx
  client/src/components/FormItem.tsx
  client/src/components/LowStockTable.tsx
  client/src/components/Modal.tsx
  client/src/components/ReserveModal.tsx
  client/src/components/SearchBar.tsx
  client/src/components/Table.tsx
  client/src/models/libraryItem.ts
  client/src/models/menuOptions.ts
  client/src/models/tableColumns.ts
  client/src/pages/Archive.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/LowStock.tsx
  client/src/pages/Overdue.tsx
  client/src/pages/Requests.tsx
  client/src/pages/SignedOut.tsx
  client/tailwind.config.js
Labels: ready for review 👀, change requested, hefty boi

#199 Search by username(for loans)
  app/resources/search.py
  app/resources/test.py
  app/resources/user.py
  app/searchFunction/trie.py
  db/db_setup/setup_db.sql
Labels: ready for review 👀

#232 PR of everything we had for the demo
  client/src/App.tsx
  client/src/PrivateRoutes.tsx
  client/src/components/AccountsTable.tsx
  client/src/components/EditModal.tsx
  client/src/components/Filter.tsx
  client/src/components/FormItem.tsx
  client/src/components/Modal.tsx
  client/src/components/SearchBar.tsx
  client/src/components/Table.tsx
  client/src/components/UserCell.tsx
  client/src/index.tsx
  client/src/models/BEModels.ts
  client/src/models/menuOptions.ts
  client/src/pages/Accounts.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/LowStock.tsx
  client/src/pages/Overdue.tsx
  client/src/pages/Requests.tsx
  client/src/pages/SignedOut.tsx
  client/src/services/SearchService.ts
  client/src/services/TestService.ts
  client/src/services/UserService.ts
  db/csv_data/item_data.csv
  db/randomizeStock.py
Labels: ready for review 👀

#233 Setup Deployment
  README.md
  app/Dockerfile.deploy
  app/app.py
  app/common/trie.py
  app/gunicorn.conf.py
  app/requirements.txt
  app/resources/search.py
  app/templates/index.html
  client/Dockerfile
  db/Dockerfile
  db/csv_data/clean_data.py
  db/csv_data/init_data.csv
  db/csv_data/item_data.csv
  db/csv_data/original_data.csv
  db/csv_data/test_data.csv
  db/db_setup/setup_db.sql
  db/randomizeStock.py
  db/requirements.txt
  docker-compose.deploy.yml
  docker-compose.yml
  package-lock.json
  proxy/Dockerfile
  proxy/nginx.conf
Labels: ready for review 👀

#242 low stock search
  client/src/PrivateRoutes.tsx
  client/src/components/LowStockTable.tsx
  client/src/components/SearchBar.tsx
  client/src/pages/LowStock.tsx
  client/src/services/TestService.ts
  db/csv_data/init_data.csv
Labels: ready for review 👀

#243 fixed archive items
  client/src/pages/Archive.tsx
  client/src/services/TestService.ts
Labels: ready for review 👀

#237 Age range fix
  client/src/App.tsx
  client/src/components/CardsModal.tsx
  client/src/components/EditModal.tsx
  client/src/components/Filter2.tsx
  client/src/components/FormItem.tsx
  client/src/components/LowStockTable.tsx
  client/src/components/Modal.tsx
  client/src/components/RangeSlider.tsx
  client/src/components/SearchBar.tsx
  client/src/components/Table.tsx
  client/src/index.tsx
  client/src/pages/AccountType.tsx
  client/src/pages/Accounts.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Overdue.tsx
  client/src/pages/SignedOut.tsx
  client/src/pages/StudentPage.tsx
Labels: ready for review 👀

#234 Notifications Set Up
  client/src/App.tsx
  client/src/components/Notification.tsx
  client/src/models/BEModels.ts
  client/src/pages/Overdue.tsx
  client/src/services/NotificationService.ts
  client/src/services/TestService.ts
Labels: ready for review 👀

#244 Add notes to tests in database
  app/resources/test.py
  app/resources/tests.py
  db/csv_data/clean_data.py
  db/db_setup/setup_db.sql
Labels: ready for review 👀, Small PR
