Repository queens-psyc-clinic/app, pull requests merged in 2024-03, with the labels that each got.

#67 FE Item Card Component
  client/src/App.tsx
  client/src/components/Card.tsx
  client/src/models/cardSampleData.ts
  client/tailwind.config.js
Labels: ready for review 👀

#69 FE Admin populated cards
  client/src/App.tsx
  client/src/components/AdminCards.tsx
  client/src/models/adminCards.ts
  client/tsconfig.json
Labels: ready for review 👀

#88 FE User Cards Modal
  client/src/components/Card.tsx
  client/src/components/CardsModal.tsx
Labels: ready for review 👀

#70 FE Add labels to navbar
  client/src/components/Navbar.tsx
  client/src/models/menuOptions.ts
Labels: ready for review 👀

#108 Restructure database
  db/clean_data.py
  db/item_data.csv
  db/original_data.csv
  db/setup_db.sql
  db/test_data.csv
Labels: ready for review 👀, urgent

#109 Main Branch Fixes
  client/src/components/Cart.tsx
  client/src/components/PillCell.tsx
  client/src/components/ReserveModal.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Overdue.tsx
  client/src/pages/SignedOut.tsx
Labels: ready for review 👀, urgent

#92 Added test controller and DELETE function to db interface
  .vscode/launch.json
  app/app.py
  app/common/db.py
  app/resources/test.py
  app/resources/tests.py
Labels: ready for review 👀

#114 Endpoints that we need
  app/Dockerfile
  app/app.py
  app/requirements.txt
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.tsx
  client/src/components/CardsModal.tsx
  client/src/models/libraryItem.ts
  client/src/services/NotificationService.ts
  client/src/services/ShoppingCartService.ts
  client/src/services/TestService.ts
  client/src/services/UserService.ts
Labels: ready for review 👀, urgent, Need Your Input

#93 Student profile page
  client/src/App.tsx
  client/src/components/DropDown.tsx
  client/src/components/DropFile.tsx
  client/src/components/Filter2.tsx
  client/src/components/Modal.tsx
  client/src/components/Table.css
  client/src/components/Table.tsx
  client/src/components/UserCell.tsx
  client/src/index.tsx
  client/src/models/Pages.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/LowStock.tsx
  client/src/pages/Overdue.tsx
  client/src/pages/SignedOut.tsx
  client/src/pages/StudentPage.tsx
  client/src/utils/urlUtils.ts
Labels: ready for review 👀

#119 [FE FIX] change location field from drop-down to text
  client/src/components/InputField.tsx
  client/src/components/Modal.tsx
  client/src/models/libraryItem.ts
Labels: ready for review 👀

#120 [FE FIX] Prune columns after "Measure" on signed-out and overdue pages
  client/src/models/tableColumns.ts
Labels: ready for review 👀

#117 [FE FIX] Low stock page prune
  client/src/models/tableColumns.ts
Labels: change requested

#123 [FE-FIX] Fixing Table Pills
  client/src/components/Table.tsx
  client/src/pages/Dashboard.tsx
Labels: ready for review 👀

#124 removed filter2
  client/src/pages/Archive.tsx
  client/src/pages/LowStock.tsx
Labels: ready for review 👀

#118 [FE FIX] drop-down filters for measure, item, age
  client/src/components/DropDown.tsx
  client/src/components/Filter.tsx
  client/src/models/libraryItem.ts
Labels: ready for review 👀

#122 Item controller updated
  app/app.py
  app/resources/createItem.py
  app/resources/item.py
  app/resources/items.py
Labels: change requested

#91 FE Sign-in/ Sign-up Pages
  client/src/App.tsx
  client/src/assets/brain.png
  client/src/assets/clinic-logo.svg
  client/src/assets/cliniclogo.png
  client/src/assets/lock.svg
  client/src/components/InputField.tsx
  client/src/index.tsx
  client/src/models/Pages.tsx
  client/src/pages/AccountType.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/utils/urlUtils.ts
Labels: ready for review 👀

#150 Search Functionality [BE]
  app/app.py
  app/resources/search.py
  app/searchFunction/trie.py
Labels: ready for review 👀

#145 FE Search Bar Placeholder
  client/src/components/SearchBar.tsx
Labels: ready for review 👀

#144 FE User Archive Page
  client/src/App.tsx
  client/src/index.tsx
  client/src/models/menuOptions.ts
  client/src/pages/Archive.tsx
Labels: ready for review 👀

#154 Change password
  app/common/db.py
  app/resources/test.py
  app/resources/tests.py
  app/resources/user.py
  app/resources/users.py
  db/clean_data.py
  db/item_data.csv
  db/test_data.csv
Labels: ready for review 👀

#158 Adjusted Add Test/ ITem functionality + Fixed the error with edit modal
  client/src/components/FormItem.tsx
  client/src/components/Modal.tsx
  client/src/components/Table.tsx
Labels: ready for review 👀, Small PR

#159 Create email notif endpoint
  app/app.py
  app/common/db.py
  app/requirements.txt
  app/resources/user.py
Labels: ready for review 👀, Small PR, Running into issue!

#187 FE Modal Changes
  client/src/components/CardsModal.tsx
  client/src/components/ConfirmModal.tsx
  client/src/components/EditModal.tsx
  client/src/components/Modal.tsx
  client/src/index.tsx
  client/src/models/BEModels.ts
  client/src/pages/AccountType.tsx
  client/src/pages/Archive.tsx
  client/src/pages/Dashboard.tsx
  client/src/pages/Overdue.tsx
  client/tailwind.config.js
Labels: ready for review 👀, big boi

#188 Add delete user endpoint
  app/resources/item.py
  app/resources/loan.py
  app/resources/test.py
  app/resources/user.py
Labels: ready for review 👀, Small PR

#192 Adjusted Search Tree
  app/resources/search.py
  app/searchFunction/trie.py
Labels: change requested, Small PR

#193 Added IsConfirmed to Loans
  app/resources/loan.py
  db/db_setup/setup_db.sql
Labels: Small PR

#178 FE Add blurb on archive item to explain
  client/src/pages/Archive.tsx
Labels: ready for review 👀

#194 Routing and Connecting Sign in and Sign Up
  app/resources/user.py
  client/src/App.tsx
  client/src/PrivateRoutes.tsx
  client/src/components/InputField.tsx
  client/src/components/Navbar.tsx
  client/src/index.tsx
  client/src/models/BEModels.ts
  client/src/models/menuOptions.ts
  client/src/pages/AccountType.tsx
  client/src/pages/LowStock.tsx
  client/src/pages/Overdue.tsx
  client/src/pages/PageNotFound.tsx
  client/src/pages/Redirect.tsx
  client/src/pages/Requests.tsx
  client/src/pages/Settings.tsx
  client/src/pages/SignIn.tsx
  client/src/pages/SignUp.tsx
  client/src/pages/SignedOut.tsx
  client/src/pages/StudentPage.tsx
  client/src/services/UserService.ts
Labels: ready for review 👀, urgent, big boi
